baseURL = "https://www.zaratan.fr"
title = "zaratan@next"
theme = "sublime-hugo-theme"
PygmentsCodeFences = true
PygmentsStyle = "solarized-dark"
pygmentsOptions="linenos=yesplease"
[params]
        languageCode = "fr"
	name = "Zaratan"
	description = "Les élucubrations d'un developpeur fatigué"
	copyright = "Zaratan Copyright ©"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Nouveau"
	older = "Ancien"

	pageNotFoundTitle = "Page non trouvée"
	pageNotFoundSubtitle = "La page que vous avez demandée <br> n'est pas attribuée."
        addThis = "ra-5c3bc29f8cb4ba57"

[params.offcanvas]
	# Menu items
	title = "Zaratan"
	bio = "Les élucubrations d'un développeur fatigué"
        bio2 = "Développeur, ludiste, admin sys, grimpeur et cuisinier à mes heures. Je suis curieux de tout, tout le temps. J’aime découvrir de nouvelles choses et les partager."
	subscribe = "Souscrire"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "denis.pasin@gmail.com"
		url = "mailto:denis.pasin@gmail.com"
